
name: Build and Deploy
on: [push, repository_dispatch]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v2  #ÂÆâË£Önode.js
        with:
          node-version: '16'
      - name: Install and Build üîß # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm install yarn --registry=https://registry.npm.taobao.org
          yarn
          yarn build
      - name: web deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_branch: gh_page
          publish_dir: ./docs
          commit_message: auto deploy
#       - name: ssh
#         uses: fifsky/ssh-action@master
#         with:
#           command: |
#             rm -rf ${{ secrets.REMOTE_TARGET }}
#           host: ${{ secrets.REMOTE_HOST }}
#           user: root
#           key: ${{ secrets.SERVER_SSH_KEY}}
#       - name: Deploy stage
#         uses: easingthemes/ssh-deploy@v2.1.2
#         env:
#           SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
#           ARGS: "-rltgoDzvO"
#           REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
#           REMOTE_USER: ${{ secrets.REMOTE_USER }}
#           SOURCE: "docs"
#           TARGET: ${{ secrets.REMOTE_TARGET }}
